/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiScoresRouteImport } from './routes/api/scores'
import { Route as ApiPlayersRouteImport } from './routes/api/players'
import { Route as ApiParseRouteImport } from './routes/api/parse'

const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoresRoute = ApiScoresRouteImport.update({
  id: '/api/scores',
  path: '/api/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayersRoute = ApiPlayersRouteImport.update({
  id: '/api/players',
  path: '/api/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseRoute = ApiParseRouteImport.update({
  id: '/api/parse',
  path: '/api/parse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRoute
  '/api/parse': typeof ApiParseRoute
  '/api/players': typeof ApiPlayersRoute
  '/api/scores': typeof ApiScoresRoute
  '/api/stats': typeof ApiStatsRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRoute
  '/api/parse': typeof ApiParseRoute
  '/api/players': typeof ApiPlayersRoute
  '/api/scores': typeof ApiScoresRoute
  '/api/stats': typeof ApiStatsRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRoute
  '/api/parse': typeof ApiParseRoute
  '/api/players': typeof ApiPlayersRoute
  '/api/scores': typeof ApiScoresRoute
  '/api/stats': typeof ApiStatsRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/champions'
    | '/api/parse'
    | '/api/players'
    | '/api/scores'
    | '/api/stats'
    | '/players/$playerId'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/champions'
    | '/api/parse'
    | '/api/players'
    | '/api/scores'
    | '/api/stats'
    | '/players/$playerId'
    | '/players'
  id:
    | '__root__'
    | '/'
    | '/champions'
    | '/api/parse'
    | '/api/players'
    | '/api/scores'
    | '/api/stats'
    | '/players/$playerId'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChampionsRoute: typeof ChampionsRoute
  ApiParseRoute: typeof ApiParseRoute
  ApiPlayersRoute: typeof ApiPlayersRoute
  ApiScoresRoute: typeof ApiScoresRoute
  ApiStatsRoute: typeof ApiStatsRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scores': {
      id: '/api/scores'
      path: '/api/scores'
      fullPath: '/api/scores'
      preLoaderRoute: typeof ApiScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/players': {
      id: '/api/players'
      path: '/api/players'
      fullPath: '/api/players'
      preLoaderRoute: typeof ApiPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse': {
      id: '/api/parse'
      path: '/api/parse'
      fullPath: '/api/parse'
      preLoaderRoute: typeof ApiParseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChampionsRoute: ChampionsRoute,
  ApiParseRoute: ApiParseRoute,
  ApiPlayersRoute: ApiPlayersRoute,
  ApiScoresRoute: ApiScoresRoute,
  ApiStatsRoute: ApiStatsRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
